---
# Роли будем устанавливать из GitHub
roles:
  # ClickHouse role
  - name: clickhouse
    src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: master
    path: roles

  # Vector role 
  - name: vector
    src: https://github.com/ArtemShtepa/vector-role.git
    scm: git
    version: main
    path: roles

  # Lighthouse role
  - name: lighthouse
    src: https://github.com/ArtemShtepa/lighthouse-role.git
    scm: git
    version: main
    path: roles

collections:
  - name: community.general
    version: ">=7.0.0"